### ISSUE TITLE
support belowLayer to place markers between layers

### ISSUE THREAD

**Issue by SteveAlexander** [emakarov/mapboxgl_notebook#2]
This is awesome :-)

I'd like to be able to put markers under the text of the map.

I think you can do this by adding a "belowLayer" parameter to the HTML, e.g. `belowLayer=" "waterway-label"`

This is what mapboxgl-jupyter does, I think.

**Comment by emakarov** [comment]
Thanks for first issue.
Try version 0.0.7 from pip
should be working. Example added in Readme

**Comment by SteveAlexander** [comment]
Thanks, this works great. I like the flexibility of being able to stack my layers declaratively.

It might be helpful to add to the docs that the layer_id referenced in below_layer_id could be one you set in your python code, or could be one that is in your mapbox theme.

**Comment by emakarov** [comment]
Ok, I will close this issue then. Regarding the docstring - I considered that the user of the library has some knowledge of mapboxgl-js, but I will consider extending the docstring later, maybe in next version. PR is also welcomed :)
